"""Change release_date Data type

Revision ID: d3a5b898f59c
Revises:
Create Date: 2021-06-13 09:45:10.317899

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3a5b898f59c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('actors', 'age',
               existing_type=sa.VARCHAR(length=3),
               nullable=False)
    op.alter_column('actors', 'gender',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('actors', 'name',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    op.alter_column('movies', 'title',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    op.alter_column('movies', 'release_date', existing_type=sa.DateTime(), type_=sa.Date())
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('movies', 'title',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    op.alter_column('actors', 'name',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    op.alter_column('actors', 'gender',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('actors', 'age',
               existing_type=sa.VARCHAR(length=3),
               nullable=True)
    # ### end Alembic commands ###
